name: Build & Push
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    permissions:
      packages: write

    uses: Accurate0/workflows/.github/workflows/build-push-docker.yaml@main
    with:
      directory: .
      image-name: "16"
      use-rust-caching: false
